### PR TITLE
fix: expressions scopes and member expressions

### PR DESCRIPTION
**Pull request by Menduist**
A few fixes, all added tests are failing on the current `develop`
I tried to simplify the `parseMemberExpression`, all tests are passing but not sure it's 100% functional

### CODE REVIEW

**Comment by Menduist** [comment]
It seems my first commit wasn't passing tests, it should now be good

**Review by TroyAlford — APPROVED** [review]
This looks great :) thanks for the contribution!

**Comment by TroyAlford** [comment]
I needed to make some more updates to fix things that your PR didn't catch, but that went in a few minutes ago and I just released v2.2.0 which includes your changes.

**Comment by Menduist** [comment]
Thanks!!

**Pull request merged**
