### PR TITLE
Move JSX parser to a plain class so it can used outside of a component

### PR DESCRIPTION
**Pull request by mallison**
In my use case I need to parse JSX at runtime but not have it coupled to a component or ReactDOM.

I have a custom reconciler so only need to generate the element tree from the JSX and use as follows.

```js
import Reconciler from 'react-reconciler';
import { JsxParser } from 'react-jsx-parser';

const hostConfig = /* ... */;
const MyRenderer = Reconciler(hostConfig);

function render(element) {
  const root = /* ... */;
  const container = MyRenderer.createContainer(root);
  MyRenderer.updateContainer(element);
}

const parser = new JsxParser();
const element = parser.parseJSX(element);
render(element);
```

I looked for a library for parsing JSX at _runtime_ but couldn't find one (I'm guessing you couldn't either so had to write your own?). The parser implemented here worked great so I forked the repo so I could just use it without the component.

Having a custom reconciler is probably not a very common use case but it could be useful to export  the parser as a plain class in addition to the component.

This PR is incomplete as I wanted to get your thoughts on doing this.

### CODE REVIEW

**Comment by TroyAlford** [comment]
You're exactly right about parsing JSX at runtime being a difficult challenge. Acorn is a great parser for ecmaScript in general, and acorn-jsx is a great parser for JSX, specifically - although I find its AST very problematic and overly complex. The TypeScript parser creates a much cleaner AST, imho, but I haven't been able to find a good way to extract it to a reasonable size for runtime usage.

I think there are a few problems with the PR, as it currently stands:

1. there are a number of unused exports/eslint issues/etc. in the different files
2. this would warrant a cleaner division between the `props` that the React Component needs vs. the `options` that the parser needs
3. there's a good bit of repetition between the two files, still, in its current form, specifically around this part related to the props

The changes are backwards compatible, so it should result in a Minor version number increase, rather than a Major, which is great. It would really be appropriate, however, to split out the unit tests to properly test the implementations of the resolver separately from those of the component (which is now a fairly simple shell around the parser).

**Comment by mallison** [comment]
Thanks for taking a look at this and apologies for taking so long to respond.

> there are a number of unused exports/eslint issues/etc. in the different files

How are you running `eslint`? When I run it I get thousands of errors which can't be right 🤔 .

> this would warrant a cleaner division between the `props` that the React Component needs vs. the `options` that the parser needs

Indeed! I've now split out the parser `options` and component `props`.

> there's a good bit of repetition between the two files, still, in its current form, specifically around this part related to the props

I've fixed the duplication by using the parser `options` defaults and type in the component.

On splitting the unit tests, would it still be reasonable to render the JSX in the parser tests? I had a quick look at using the raw element tree but rendering the JSX gives a much nicer API to assert against.

**Comment by TroyAlford** [comment]
Oof... now it's me who took a long time to respond. I apologize for that.

It does seem reasonable to render the JSX in order to assert, yes. That'll let you cleanly use `enzyme`, rather than trying to re-parse the output or the tree or anything, and I think it verifies nicely.

RE: `eslint`, I just pushed an update to `develop` which contains a `lint` script. You can just run `yarn lint` and it'll run the linter. It will also now be run alongside the `test` command, so CI will automatically lint as part of the PR process going forward.

**Comment by TroyAlford** [comment]
Closing this, for now, due to inactivity.

**Pull request closed without merging**
