### PR TITLE
Keep white-space as authored, so non-breaking spaces are rendered as such

### LINKED ISSUE #31: Non-breaking spaces replaced with regular, breaking spaces
The parser seems to replace non breaking spaces by normal spaces, I've tried using regular html entities, unicode characters, and hard-coding the non breaking spaces (typing alt + space on a Mac), no matter what I cannot get a non-breaking space in the parser output.

## Reproducing the issue
Compare the render of `<JsxParser>` with React's `dangerouslySetInnerHtml` prop using the following:

### Input
```html
<p>This is a « test » without any non-breaking space</p>
<p>This is a «\u00a0test\u00a0» with non-breaking spaces as Unicode character</p>
<p>This is a «&nbsp;test&nbsp;» with non-breaking spaces as regular html entities</p>
```

You can also try with hard-coded non-breaking spaces but it seems I cannot type nor paste them in github's editor for some reason, so I didn't include this in the example input

### Output
With `<JsxParser>` you should get regular spaces everywhere, with `dangerouslySetInnerHtml` you should get the non-breaking spaces wherever you put them, which is the expected behavior.

## Version info
I'm using React 15.6.1 and react-jsx-parser 1.1.5

### PR DESCRIPTION
**Pull request by daformat**
Fixes #31

### CODE REVIEW

**Comment by TroyAlford** [comment]
Thanks a bunch for the pull request! For some reason CircleCI is failing, and unfortunately I'm out of town at the moment, so I can't debug it immediately. The changes and the new test look good to me, I just want to see CI pass - and then I will push a new version.

Sorry for the delay!

**Comment by daformat** [comment]
Sure no worries, I'll keep using my fork until then.

**Comment by TroyAlford** [comment]
Sorry for the delay on getting this merged and released! It'll be going out in the next few minutes. :) Thanks for the awesome contribution!

**Comment by TroyAlford** [comment]
v1.1.6 is now live, if you'd like to refer to it.

**Pull request merged**
