### PR TITLE
bugfix: option tag returns wrong content

### PR DESCRIPTION
**Pull request by rostber**
Issue https://github.com/TroyAlford/react-jsx-parser/issues/196

### CODE REVIEW

**Comment by TroyAlford** [comment]
Huh. Pretty fascinating error. Thanks for the PR!

**Comment by TroyAlford** [comment]
Could you please also bump the version number? This is a bugfix, so it's the patch that should update. Once that's done, I'll release as `1.28.4`

**Comment by rostber** [comment]
@TroyAlford done

**Comment by TroyAlford** [comment]
Released as `1.28.4` just now

**Pull request merged**
