### PR TITLE
Add onError callback

### PR DESCRIPTION
**Pull request by dan-lee**
I'd like to be able show an error message in some manner in the fronend, if parsing failed.
So I added an `onError` callback to the props which will solve this :).

### CODE REVIEW

**Comment by TroyAlford** [comment]
Nice enhancement! Thanks!

**Comment by TroyAlford** [comment]
@dan-lee - FYI - I just released version 1.1.2 so that the public package includes your change. :) Please feel free to update your `package.json` and update now!

**Comment by dan-lee** [comment]
@TroyAlford cool thank you 🚀
Great module, btw :)

**Comment by TroyAlford** [comment]
Thanks! Glad you're enjoying it! :)

**Pull request merged**
